## Title: NumPy Assignment
In this assignment, you'll practice using NumPy to solve a problem. You have been given a dataset that represents the height (in centimeters) of 10 students in a class.

### Dataset:

 heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])
Your task is to:

1. Calculate the mean, median, and standard deviation of the students' heights.

2. Create a new array with the heights normalized, i.e., each height value should be transformed to have a mean of 0 and a standard deviation of 1.

3. Determine the tallest and shortest students in the class using NumPy's argmax and argmin functions.

4. Calculate the difference between the tallest and shortest students' heights.

5. Randomly select 5 heights from the dataset without replacement.

6. Complete the assignment by writing Python code using NumPy. Remember to first import NumPy and use its functions to perform the required calculations. Good luck!

* Note: The purpose of this assignment is to test your understanding of NumPy concepts covered in this curriculum. Try to complete the assignment without referring back to the curriculum, but if you get stuck, feel free to review the topics and examples provided.



In [1]:
import numpy as np

In [3]:
heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])
heights

array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])

#### Mean

In [4]:
mean = np.mean(heights)
mean

166.7

#### Median

In [5]:
median = np.median(heights)
median

166.5

#### Mode

In [10]:
from scipy import stats
mode = stats.mode(heights, keepdims=True)
mode

ModeResult(mode=array([155]), count=array([1]))

#### Standard Deviation

In [13]:
std_dev = np.std(heights)
std_dev

7.5372408744845085

#### Normalized Height
Create a new array with the heights normalized, i.e., each height value should be transformed to have a mean of 0 and a standard deviation of 1.

In [15]:
normalized_heights = (heights - mean) / std_dev
normalized_heights

array([-0.88891945, -1.55229217,  0.70317509, -0.22554673,  1.76457144,
       -1.15426854,  1.10119872, -0.49089581,  0.57050054,  0.17247691])

#### argmax and argmin
Determine the tallest and shortest students in the class using NumPy's argmax and argmin functions.

In [18]:
heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])
heights

array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])

In [24]:
max_idx = np.argmax(heights) #Returns the index of the element with the highest value
max_height = heights[max_idx] #print the element
max_height

180

In [25]:
min_idx = np.argmin(heights)
min_height = heights[min_idx]
min_height

155

Calculate the difference between the tallest and shortest students' heights.

In [26]:
difference = max_height - min_height
difference

25

#### Random Selection

Randomly select 5 heights from the dataset without replacement.

In [44]:
random = np.random.choice(heights, 5, replace=False)
random

array([158, 180, 171, 155, 168])